import { Achievement, Challenge, LeaderboardEntry, Party } from '@/types';

// Initial Achievements
export const initialAchievements: Achievement[] = [
  // Fitness Achievements
  {
    id: 'ach_first_steps',
    title: 'First Steps',
    description: 'Take your first 1,000 steps',
    icon: '👣',
    rarity: 'common',
    category: 'fitness',
    unlocked: false,
    progress: 0,
    target: 1000,
    xpReward: 50,
    goldReward: 25,
    hidden: false,
  },
  {
    id: 'ach_walker',
    title: 'Daily Walker',
    description: 'Reach 10,000 steps in a single day',
    icon: '🚶',
    rarity: 'uncommon',
    category: 'fitness',
    unlocked: false,
    progress: 0,
    target: 10000,
    xpReward: 100,
    goldReward: 50,
    hidden: false,
  },
  {
    id: 'ach_marathon',
    title: 'Marathon Master',
    description: 'Walk 100,000 steps total',
    icon: '🏃',
    rarity: 'rare',
    category: 'fitness',
    unlocked: false,
    progress: 0,
    target: 100000,
    xpReward: 500,
    goldReward: 250,
    hidden: false,
  },
  {
    id: 'ach_workout_warrior',
    title: 'Workout Warrior',
    description: 'Complete 30 minutes of exercise',
    icon: '💪',
    rarity: 'uncommon',
    category: 'fitness',
    unlocked: false,
    progress: 0,
    target: 30,
    xpReward: 150,
    goldReward: 75,
    hidden: false,
  },
  
  // Meditation Achievements
  {
    id: 'ach_zen_beginner',
    title: 'Zen Beginner',
    description: 'Meditate for 5 minutes',
    icon: '🧘',
    rarity: 'common',
    category: 'mindfulness',
    unlocked: false,
    progress: 0,
    target: 5,
    xpReward: 50,
    goldReward: 25,
    hidden: false,
  },
  {
    id: 'ach_mindful_master',
    title: 'Mindful Master',
    description: 'Complete 100 minutes of meditation',
    icon: '🧘',
    rarity: 'epic',
    category: 'mindfulness',
    unlocked: false,
    progress: 0,
    target: 100,
    xpReward: 300,
    goldReward: 150,
    hidden: false,
  },
  
  // Nutrition Achievements
  {
    id: 'ach_meal_logger',
    title: 'Meal Logger',
    description: 'Log your first meal',
    icon: '🍽️',
    rarity: 'common',
    category: 'nutrition',
    unlocked: false,
    progress: 0,
    target: 1,
    xpReward: 25,
    goldReward: 10,
    hidden: false,
  },
  {
    id: 'ach_nutrition_tracker',
    title: 'Nutrition Tracker',
    description: 'Log 30 meals',
    icon: '🥗',
    rarity: 'rare',
    category: 'nutrition',
    unlocked: false,
    progress: 0,
    target: 30,
    xpReward: 200,
    goldReward: 100,
    hidden: false,
  },
  {
    id: 'ach_hydration_hero',
    title: 'Hydration Hero',
    description: 'Drink 8 glasses of water in a day',
    icon: '💧',
    rarity: 'uncommon',
    category: 'hydration',
    unlocked: false,
    progress: 0,
    target: 8,
    xpReward: 100,
    goldReward: 50,
    hidden: false,
  },
  
  // Sleep Achievements
  {
    id: 'ach_good_sleep',
    title: 'Good Sleep',
    description: 'Get 7-9 hours of sleep',
    icon: '😴',
    rarity: 'common',
    category: 'sleep',
    unlocked: false,
    progress: 0,
    target: 1,
    xpReward: 50,
    goldReward: 25,
    hidden: false,
  },
  {
    id: 'ach_sleep_champion',
    title: 'Sleep Champion',
    description: 'Maintain good sleep for 7 days',
    icon: '🌙',
    rarity: 'epic',
    category: 'sleep',
    unlocked: false,
    progress: 0,
    target: 7,
    xpReward: 300,
    goldReward: 150,
    hidden: false,
  },
  
  // Streak Achievements
  {
    id: 'ach_streak_3',
    title: '3-Day Warrior',
    description: 'Maintain a 3-day streak',
    icon: '🔥',
    rarity: 'common',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 3,
    xpReward: 75,
    goldReward: 35,
    hidden: false,
  },
  {
    id: 'ach_streak_7',
    title: 'Week Warrior',
    description: 'Maintain a 7-day streak',
    icon: '🔥',
    rarity: 'uncommon',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 7,
    xpReward: 150,
    goldReward: 75,
    hidden: false,
  },
  {
    id: 'ach_streak_30',
    title: 'Month Master',
    description: 'Maintain a 30-day streak',
    icon: '🔥',
    rarity: 'epic',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 30,
    xpReward: 500,
    goldReward: 250,
    hidden: false,
  },
  {
    id: 'ach_streak_100',
    title: 'Century Legend',
    description: 'Maintain a 100-day streak',
    icon: '🔥',
    rarity: 'legendary',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 100,
    xpReward: 1000,
    goldReward: 500,
    hidden: false,
  },
  
  // Quest Achievements
  {
    id: 'ach_first_quest',
    title: 'Quest Beginner',
    description: 'Complete your first quest',
    icon: '📜',
    rarity: 'common',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 1,
    xpReward: 50,
    goldReward: 25,
    hidden: false,
  },
  {
    id: 'ach_quest_master',
    title: 'Quest Master',
    description: 'Complete 50 quests',
    icon: '⚔️',
    rarity: 'rare',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 50,
    xpReward: 400,
    goldReward: 200,
    hidden: false,
  },
  {
    id: 'ach_quest_legend',
    title: 'Quest Legend',
    description: 'Complete 200 quests',
    icon: '👑',
    rarity: 'legendary',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 200,
    xpReward: 1500,
    goldReward: 750,
    hidden: false,
  },
  
  // Level Achievements
  {
    id: 'ach_level_5',
    title: 'Novice Adventurer',
    description: 'Reach level 5',
    icon: '⭐',
    rarity: 'uncommon',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 5,
    xpReward: 100,
    goldReward: 50,
    hidden: false,
  },
  {
    id: 'ach_level_10',
    title: 'Skilled Hero',
    description: 'Reach level 10',
    icon: '⭐',
    rarity: 'rare',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 10,
    xpReward: 250,
    goldReward: 125,
    hidden: false,
  },
  {
    id: 'ach_level_20',
    title: 'Elite Champion',
    description: 'Reach level 20',
    icon: '⭐',
    rarity: 'epic',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 20,
    xpReward: 500,
    goldReward: 250,
    hidden: false,
  },
  {
    id: 'ach_level_30',
    title: 'Legendary Master',
    description: 'Reach the maximum level',
    icon: '⭐',
    rarity: 'legendary',
    category: 'custom',
    unlocked: false,
    progress: 0,
    target: 30,
    xpReward: 1000,
    goldReward: 500,
    hidden: false,
  },
];

// Mock Leaderboard Data
export const mockLeaderboard: LeaderboardEntry[] = [
  {
    rank: 1,
    userId: 'user_1',
    username: 'HealthWarrior',
    level: 15,
    totalXp: 8500,
    avatar: { skin: 'default', hair: 'default', outfit: 'default', accessories: [] },
    change: 0,
  },
  {
    rank: 2,
    userId: 'user_2',
    username: 'FitQuest',
    level: 14,
    totalXp: 7250,
    avatar: { skin: 'default', hair: 'default', outfit: 'default', accessories: [] },
    change: 1,
  },
  {
    rank: 3,
    userId: 'user_3',
    username: 'ZenMaster',
    level: 13,
    totalXp: 6100,
    avatar: { skin: 'default', hair: 'default', outfit: 'default', accessories: [] },
    change: -1,
  },
  {
    rank: 4,
    userId: 'user_4',
    username: 'StepChampion',
    level: 12,
    totalXp: 5050,
    avatar: { skin: 'default', hair: 'default', outfit: 'default', accessories: [] },
    change: 2,
  },
  {
    rank: 5,
    userId: 'user_5',
    username: 'MindfulHero',
    level: 11,
    totalXp: 4100,
    avatar: { skin: 'default', hair: 'default', outfit: 'default', accessories: [] },
    change: 0,
  },
];

// Mock Parties
export const mockParties: Party[] = [
  {
    id: 'party_1',
    name: 'Morning Warriors',
    description: 'Early risers who conquer their fitness goals before breakfast!',
    members: [
      {
        userId: 'user_1',
        username: 'HealthWarrior',
        level: 15,
        avatar: { skin: 'default', hair: 'default', outfit: 'default', accessories: [] },
        role: 'leader',
        joinedAt: new Date('2024-01-01'),
      },
      {
        userId: 'user_2',
        username: 'FitQuest',
        level: 14,
        avatar: { skin: 'default', hair: 'default', outfit: 'default', accessories: [] },
        role: 'member',
        joinedAt: new Date('2024-01-05'),
      },
    ],
    currentQuest: {
      questId: 'party_quest_1',
      title: 'Collective 100K Steps',
      description: 'Walk 100,000 steps together as a party',
      totalProgress: 45000,
      targetProgress: 100000,
      startedAt: new Date('2024-12-01'),
      endsAt: new Date('2024-12-07'),
      rewards: {
        xp: 500,
        gold: 250,
      },
    },
    createdAt: new Date('2024-01-01'),
    maxMembers: 10,
  },
  {
    id: 'party_2',
    name: 'Zen Squad',
    description: 'Meditation and mindfulness enthusiasts',
    members: [
      {
        userId: 'user_3',
        username: 'ZenMaster',
        level: 13,
        avatar: { skin: 'default', hair: 'default', outfit: 'default', accessories: [] },
        role: 'leader',
        joinedAt: new Date('2024-01-10'),
      },
    ],
    createdAt: new Date('2024-01-10'),
    maxMembers: 8,
  },
];

// Mock Challenges
export const mockChallenges: Challenge[] = [
  {
    id: 'challenge_1',
    title: 'December Step Challenge',
    description: 'Walk 300,000 steps this month!',
    type: 'global',
    category: 'fitness',
    startDate: new Date('2024-12-01'),
    endDate: new Date('2024-12-31'),
    participants: 1247,
    rewards: {
      xp: 1000,
      gold: 500,
      items: ['legendary_badge'],
    },
    progress: 45000,
    target: 300000,
  },
  {
    id: 'challenge_2',
    title: 'Mindful December',
    description: 'Meditate for 500 minutes this month',
    type: 'global',
    category: 'mindfulness',
    startDate: new Date('2024-12-01'),
    endDate: new Date('2024-12-31'),
    participants: 823,
    rewards: {
      xp: 800,
      gold: 400,
    },
    progress: 120,
    target: 500,
  },
  {
    id: 'challenge_3',
    title: 'Weekly Workout Blitz',
    description: 'Complete 150 minutes of exercise this week',
    type: 'solo',
    category: 'fitness',
    startDate: new Date('2024-12-02'),
    endDate: new Date('2024-12-08'),
    participants: 2341,
    rewards: {
      xp: 300,
      gold: 150,
    },
    progress: 60,
    target: 150,
  },
];

// Motivational Messages for AI Coach
export const motivationalMessages = [
  "You're doing amazing! Keep up the great work!",
  "Every step counts towards your goals!",
  "Consistency is key to success!",
  "You're stronger than you think!",
  "Small progress is still progress!",
  "Your future self will thank you!",
  "One day at a time, one quest at a time!",
  "You've got this, champion!",
  "Your dedication is inspiring!",
  "Keep pushing forward, warrior!",
  "Health is wealth, and you're investing wisely!",
  "Your streak is on fire! Don't break it now!",
  "Remember why you started!",
  "You're building a healthier, happier you!",
  "Every workout is a victory!",
];

// Tips for different categories
export const healthTips = {
  fitness: [
    "Try to take short walking breaks every hour",
    "Stairs are a great way to add extra steps to your day",
    "Morning workouts can boost your energy for the whole day",
    "Consistency beats intensity - aim for daily movement",
    "Track your progress to stay motivated",
  ],
  nutrition: [
    "Drink water before meals to aid digestion",
    "Plan your meals ahead to make healthier choices",
    "Include colorful vegetables in every meal",
    "Mindful eating helps you enjoy food more",
    "Protein with every meal helps maintain energy",
  ],
  mindfulness: [
    "Start with just 5 minutes of meditation daily",
    "Focus on your breath when feeling stressed",
    "Practice gratitude to boost mental well-being",
    "Take mindful breaks throughout the day",
    "Meditation improves focus and reduces anxiety",
  ],
  sleep: [
    "Aim for 7-9 hours of sleep each night",
    "Keep a consistent sleep schedule",
    "Avoid screens 1 hour before bedtime",
    "Create a relaxing bedtime routine",
    "A cool, dark room promotes better sleep",
  ],
  hydration: [
    "Drink water first thing in the morning",
    "Keep a water bottle with you at all times",
    "Set reminders to drink water throughout the day",
    "Herbal teas count towards your hydration goal",
    "Your body needs water for every function",
  ],
};
